site_name: LoRAX Docs
theme:
  name: material
  font:
    text: Roboto
  features:
    - navigation.sections
    - navigation.indexes
    - search.suggest
    - search.highlight
  logo: images/lorax_guy.png
  favicon: favicon.ico
  palette:
    # primary: deep orange
    # accent: deep orange
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: deep orange
      accent: deep orange

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: deep orange
      accent: deep orange

nav:
  - LoRAX: index.md
  - 🚀 Getting Started:
      - Docker: getting_started/docker.md
      - Kubernetes (Helm): getting_started/kubernetes.md
      - SkyPilot: getting_started/skypilot.md
      - Local: getting_started/local.md
  - 🧮 Models:
      - Base Models: models/base_models.md
      - Adapters:
          - Adapters: models/adapters/index.md
          - LoRA: models/adapters/lora.md
          - Medusa: models/adapters/medusa.md
  - 📚 Reference:
      - Launcher: reference/launcher.md
      - REST API: reference/rest_api.md
      - Python Client:
          - Python Client: reference/python_client/index.md
          - lorax.client: reference/python_client/client.md
        # - lorax.types: reference/python_client/types.md
      - OpenAI Compatible API: reference/openai_api.md
      - Metrics: reference/metrics.md
  - 🔬 Guides:
      - Quantization: guides/quantization.md
      - Structured Output (JSON): guides/structured_output.md
      - Speculative Decoding: guides/speculative_decoding.md
      - CUDA Graph Compilation: guides/cuda_graphs.md
      - Merging Adapters: guides/merging_adapters.md
      - Contributing to LoRAX:
          - Contributing to LoRAX: guides/contributing/index.md
          - Development Environment: guides/contributing/development_env.md
  #     - GPUs: guides/gpus.md
  #     - Fine-Tuning: guides/fine_tuning.md
  #     - Memory Management: guides/memory_management.md
  #     - Storage: guides/storage.md

repo_url: https://github.com/predibase/lorax
repo_name: predibase/lorax

copyright: Copyright &copy; 2023 Predibase, Inc.
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/predibase/lorax
    - icon: fontawesome/brands/discord
      link: https://discord.gg/CBgdrGnZjy

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - render_swagger
  - search
