name: LoRAX Integration Tests
description: Run integration tests for LoRAX
inputs:
  test_image_tag:
    description: 'LoRAX Docker image tag to test'
    required: true
    type: string
  use_local_image:
    description: 'Use local image instead of GitHub Container Registry'
    required: false
    type: boolean

runs:
  using: 'composite'
  steps:

    - name: Print Test Image Tag
      run: |
        echo "Test image tag: ${{ inputs.test_image_tag }}"

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest docker requests

    - name: Login to GitHub Container Registry
      if: ${{ !inputs.use_local_image }}
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up environment variables
      run: |
        echo "HUGGING_FACE_HUB_TOKEN=${{ secrets.HUGGING_FACE_HUB_TOKEN }}" >> $GITHUB_ENV
        echo "TEST_IMAGE_TAG=${{ inputs.test_image_tag }}" >> $GITHUB_ENV

    - name: Run Embedding tests
      run: |
        cd integration-tests-2
        pytest test_embeddings.py -v --capture=tee-sys

    - name: Run LLM tests
      run: |
        cd integration-tests-2
        pytest test_base_llms.py -v --capture=tee-sys
