name: Build and push docker image with soci indexes to ghcr

on:
  workflow_dispatch:
  push:
    branches:
      - 'INFRA-2132-soci'

jobs:
  build-and-push-image:
    concurrency:
      group: ${{ github.workflow }}-${{ github.job }}-${{ github.head_ref || github.run_id }}
      cancel-in-progress: true
    runs-on: a100-runner
    permissions:
      contents: write
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: false
          swap-storage: true
        
      - name: Install soci
        uses: lerentis/soci-installer@v1.0.1
        with:
          soci-release: 'v0.4.0'
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.10.0

      - name: Set up containerd for ubuntu
        uses: crazy-max/ghaction-setup-containerd@v2.2.0

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/predibase/lorax
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,prefix=,suffix=,format=short
            type=raw,value=latest
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}
      
      # - name: Build Docker image
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: .
      #     file: ./Dockerfile  # Path to your Dockerfile
      #     push: false
      #     tags: ${{ steps.meta.outputs.tags }}
      #     outputs: type=oci,dest=/tmp/lorax-${{ steps.meta.outputs.version }}.tar

      - name: Import image in containerd
        run: |
          tags=${{ steps.meta.outputs.tags }}
          echo $tags
          for tag in tags
          do
            sudo ctr i import --base-name ghcr.io/predibase/lorax:$tag --digests /tmp/lorax-${{ steps.meta.outputs.version }}.tar
          done
          # rm -rf /tmp/lorax-${{ steps.meta.outputs.version }}.tar

      - name: Push image with containerd
        run: |
          for tag in ${{ steps.meta.outputs.tags }}
          do
            sudo ctr i import --base-name ghcr.io/predibase/lorax:$tag --digests /tmp/lorax-${{ steps.meta.outputs.version }}.tar
            sudo ctr i push --user "${{ github.repository_owner }}:${{ secrets.GHCR_PAT }}" ghcr.io/predibase/lorax:$tag
          done

      - name: Create and push soci index
        run: |
          for tag in ${{ steps.meta.outputs.tags }}
          do
            sudo soci create ghcr.io/predibase/lorax:$tag
            sudo soci push --user ${{ github.repository_owner }}:${{ secrets.GHCR_PAT }} ghcr.io/predibase/lorax:$tag
          done
