name: Mistral Integration Tests

on:
  push:
    branches: [ main, integration-tests-main]
  workflow_dispatch:

jobs:
  test:
    runs-on: a100-40gb-runner

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest docker requests

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up environment variables
      run: |
        echo "HUGGING_FACE_HUB_TOKEN=${{ secrets.HUGGING_FACE_HUB_TOKEN }}" >> $GITHUB_ENV
        echo "LORAX_IMAGE_TAG=${{ secrets.HUGGING_FACE_HUB_TOKEN }}" >> $GITHUB_ENV

    - name: Run Embedding tests
      run: |
        cd integration-tests-2
        pytest test_embeddings.py -v --capture=tee-sys

    - name: Run LLM tests
      run: |
        cd integration-tests-2
        pytest test_base_llms.py -v --capture=tee-sys
