name: Server Tests

on:
  pull_request:
    paths:
      - ".github/workflows/server_tests.yaml"
      - "server/**"
      - "proto/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Adding actions/checkout@v2
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.10"
      - name: Get changed files
        id: changed_files
        run: |
          echo "files=$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep -E '*.py$' | tr '\n' ' ')"
          echo "files=$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep -E '*.py$' | tr '\n' ' ')" >> $GITHUB_OUTPUT

      # TODO(travis): reenable after running this on the entire codebase
      # - name: Run flake8 on changed files
      #   if: steps.changed_files.outputs.files != ''
      #   run: |
      #     pip install flake8
      #     echo running linter on: ${{ steps.changed_files.outputs.files }}
      #     flake8 ${{ steps.changed_files.outputs.files }}

      - name: Install Protoc
        uses: arduino/setup-protoc@v1
      - name: Filter test dependencies
        run: |
          # remove stanford-stk from test requirements as it cannot install correctly without GPUs
          sed -i '/stanford-stk/d' server/requirements.txt
          sed -i '/stanford-stk/d' server/pyproject.toml
      - name: Install
        run: |
          make install-server install-custom-kernels
      - name: Run server tests
        run: |
          pip install pytest
          export HUGGING_FACE_HUB_TOKEN=${{ secrets.HUGGING_FACE_HUB_TOKEN }}
          pytest -s -vv server/tests
