name: Server Tests

on:
  pull_request:
    paths:
      - ".github/workflows/server_tests.yaml"
      - "server/**"
      - "proto/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.10"
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
      - name: Filter test dependencies
        run: |
          # remove stanford-stk from test requirements as it cannot install correctly without GPUs
          sed -i '/stanford-stk/d' server/requirements.txt
          sed -i '/stanford-stk/d' server/pyproject.toml
      - name: Install
        run: |
          make install-server install-custom-kernels
      - name: Run server tests
        run: |
          pip install pytest
          export HUGGING_FACE_HUB_TOKEN=${{ secrets.HUGGING_FACE_HUB_TOKEN }}
          pytest -s -vv server/tests
